src/Entity/SubCategory.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SubCategoryRepository")
 */
class SubCategory
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @var Survey[]|Collection
     *
     * @ORM\OneToMany(
     *      targetEntity="Survey",
     *      mappedBy="subCategory"
     * )
     */
    private $surveys;

    /** @var int */
    private $nbSurveySuccess;

    /** @var int */
    private $nbSuccess;

    public function __construct()
    {
        $this->surveys = new ArrayCollection();
        $this->initializeIncrement();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): void
    {
        $this->category = $category;
    }

    public function getSurveys(): Collection
    {
        return $this->surveys;
    }

    public function addSurvey(Survey $survey): void
    {
        $survey->setSubCategory($this);
        if (!$this->surveys->contains($survey)) {
            $this->surveys->add($survey);
        }
    }

    public function removeSurvey(Survey $survey): void
    {
        $this->surveys->removeElement($survey);
    }

    public function getNbSurveySuccess(): int
    {
        return $this->nbSurveySuccess;
    }

    public function initializeIncrement(): void
    {
        $this->nbSurveySuccess = 0;
        $this->nbSuccess = 0;
    }

    public function incrementNbSurveySuccess(int $nb): void
    {
        $this->nbSurveySuccess = $this->nbSurveySuccess + $nb;
    }

    public function getNbSuccess(): int
    {
        return $this->nbSuccess;
    }

    public function incrementNbSuccess(bool $success): void
    {
        if($success){
            $this->nbSuccess ++;
        }
    }

    public function getSurveysActive(): Collection
    {
        return $this->getSurveys()->filter(function (Survey $survey){
            return $survey->isStatus();
        });
    }

    public function getCompletionPercent(): int
    {
        if($this->getNbSuccess() >= $this->getSurveysActive()->count()){
            return 100;
        }
        return ceil(($this->getNbSuccess()/$this->getSurveysActive()->count()) * 100);
    }
}

templates/index/category.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <div class="row p-3">
        <div class="col-sm-10">
            <h1>{{ 'title.category'|trans }} {{ category.title }}</h1>
        </div>

        <div class="col-sm-2">
            <a href="{{ path('homepage') }}">
                <h2><i class="fa fa-undo" aria-hidden="true"></i> {{ 'action.back'|trans }}</h2>
            </a>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-10">
            {% for subCategory in subCategories %}
                {% if subCategory.surveysActive.count %}
                    <a href="{{ path('sub_category', {id: category.id, sub_id: subCategory.id}) }}"
                       class="btn btn-block {{ subCategory.getCompletionPercent == 100 ? 'btn-success' :'btn-info' }}">
                        <div class="row">
                            <div class="col-md-4">
                                {{ subCategory.title }}
                            </div>

                            <div class="col-md-3 text-center">
                                {{ 'survey.test_success'|trans }} {{ subCategory.nbSurveySuccess }}
                            </div>
                            <div class="col-md-3 text-center">
                                {{ 'survey.survey_success'|trans }} {{ subCategory.nbSuccess }}
                                /{{ subCategory.surveysActive.count }}
                            </div>

                            <div class="col-md-2">
                                {{ subCategory.getCompletionPercent }}% {{ 'survey.display_end'|trans }}
                            </div>
                        </div>
                    </a>
                {% endif %}
            {% else %}
                <div align="center">{{ 'sub_category.no_sub_categories_found'|trans }}</div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <h1>{{ 'title.index'|trans }} </h1>

    <div class="row">
        <div class="col-lg-10">
            {% for category in categories %}
                {% if category.getTotalSurveys %}
                    <a href="{{ path('category', {id: category.id}) }}"
                       class="btn btn-block {{ category.getCompletionPercent == 100 ? 'btn-success' :'btn-info' }}">
                        <div class="row">
                            <div class="col-md-4">
                                {{ category.title }}
                            </div>

                            <div class="col-md-3 text-center">
                                {{ 'survey.test_success'|trans }} {{ category.nbSurveySuccess }}
                            </div>
                            <div class="col-md-3 text-center">
                                {{ 'survey.survey_success'|trans }} {{ category.nbSuccess }}
                                /{{ category.getTotalSurveys }}
                            </div>

                            <div class="col-md-2">
                                {{ category.getCompletionPercent }}% {{ 'survey.display_end'|trans }}
                            </div>
                        </div>
                    </a>
                {% endif %}

            {% else %}
                <div align="center">{{ 'category.no_categories_found'|trans }}</div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

templates/index/sub_category.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <div class="row p-3">
        <div class="col-sm-10">
            <h1>{{ 'title.category'|trans }} {{ subCategory.category.title }} - {{ subCategory.title }}</h1>
        </div>

        <div class="col-sm-2">
            <a href="{{ path('category', {id: subCategory.category.id}) }}">
                <h2><i class="fa fa-undo" aria-hidden="true"></i> {{ 'action.back'|trans }}</h2>
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-10">
            {% for survey in surveys %}
                <a href="{{ path('survey', {id: survey.id}) }}" class="btn btn-block {{ survey.getCompletionPercent == 100 ? 'btn-success' :'btn-info' }}">
                    <div class="row">
                        <div class="col-md-6">
                            {{ survey.title }}
                        </div>

                        <div class="col-md-4 text-center">
                            {{ 'survey.test_success'|trans }} {{ survey.nbSurveySuccess }}/{{ survey.NbSurveysToPass }}
                        </div>

                        <div class="col-md-2">
                            {{ survey.getCompletionPercent }}% {{ 'survey.display_end'|trans }}
                        </div>
                    </div>
                </a>

            {% else %}
                <div align="center">{{ 'survey.no_surveys_found'|trans }}</div>
            {% endfor %}
        </div>
    </div>


{% endblock %}